name: kubectl
on:
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: determine location of kubectl
        run: |
          echo "kubectl version"
          kubectl version
          which kubectl

          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl
          mv kubectl $(which kubectl)