name: kubectl
on:
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: determine location of kubectl
        run: |
          echo "kubectl version"
          kubectl version --client=true
          which kubectl

      - name: Install version 1.23.6 kuebctl
        uses: azure/setup-kubectl@6025c840858f1afa584a5190a4426c338f59e503
        with:
          version: 'v1.23.6' # default is latest stable
      
      - name: Check version again
        run: |
          kubectl version --client=true

